#app.yaml
runtime: nodejs18

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "fishguard-key69.json"
  JWT_SECRET: "fishguardslebew69"
  BUCKET_NAME: "fish-img-data"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*  # Menangani semua rute lainnya dengan aplikasi Node.js
    script: auto

instance_class: F2

env: standard